alias br='sudo systemctl suspend'
alias logout='i3-msg exit'
alias dbg='cd ~/dev/Dragonball-Germany'
alias hn='cd ~/dev/Home-Nexus'
alias neovide='nohup /usr/local/bin/neovide > /dev/null 2>&1 & disown'
